# Generated by Django 4.0.3 on 2022-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_citizens_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
