# Generated by Django 4.0.3 on 2022-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('zipcode', models.IntegerField(null=True)),
                ('land_line', models.IntegerField()),
                ('cellular', models.IntegerField()),
                ('is_infected', models.BooleanField(default=False)),
                ('conditions', models.TextField(max_length=40)),
            ],
        ),
    ]
