# Generated by Django 4.0.3 on 2022-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizens',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
